################################# Default configuration ###################
# provide your domain here
baseURL = "https://snalab.netlify.app/"
# theme
theme = "dot"
# site title
title = "SNA Lab | @Harrisburg"
# disable language
disableLanguages = []
# google analytics
googleAnalytics = "" # paste your analytics ID here. (Ex: UA-123-45)
# unsafe html
[markup.goldmark.renderer]
unsafe = true


############################# Default Parameters ##########################
[params]
# logo is for all page
logo = ""
# logo white is for homepage logo, you can use colorful logo too...
logo_white = ""
# when logo is empty, it will shown your site title

# customize color
primary_color = "#02007e"
body_color = "#f9f9f9"
text_color = "#636363"
text_color_dark = "#242738"
white_color = "#ffffff"
light_color = "#f8f9fa"

# font family
font_family = "lato" # Choose font family from : https://fonts.google.com/

# contact form action
contact_form_action = "https://formspree.io/f/moqpeyao" # contact form works with : https://formspree.io


############################## social links ##############################
[[params.social]]
icon = "ti-github" # themify icon pack : https://themify.me/themify-icons
link = "https://github.com/SNAL-HB"

#[[params.social]]
#icon = "ti-twitter-alt" # themify icon pack : https://themify.me/themify-icons
#link = "#"

#[[params.social]]
#icon = "ti-github" # themify icon pack : https://themify.me/themify-icons
#link = "#"

#[[params.social]]
#icon = "ti-linkedin" # themify icon pack : https://themify.me/themify-icons
#link = "#"

################################ English Language ######################
[Languages.en]
languageName = "En"
languageCode = "en-us"
weight = 1
copyright = "Copyright © 2020 Social Network Analysis Lab at Harrisburg | [Contact](mailto:hartbullock@psu.edu)"

# banner
[Languages.en.params.banner]
title = "Collobrate=Experiment + Workshop"
subtitle = "Get advice and feedback from our SNA community fast and keep in touch"
bg_image = "images/banner.jpg"
placeholder = "Ready? Why not start your SNA journey here"

# call to action
[Languages.en.params.cta]
enable = true
title = "Want to participate in our lab?"
content = "Feel free to check our ongoing projects and pitch your own topics."
# call to action button
[Languages.en.params.cta.button]
enable = true
label = "Join us"
link = "signup"


################## english navigation #################
[[Languages.en.menu.main]]
name = "Home"
url = "/"
weight = 1

[[Languages.en.menu.main]]
name = "People"
url = "/people"
weight = 2

[[Languages.en.menu.main]]
name = "FAQ"
url = "faq"
weight = 3

[[Languages.en.menu.main]]
name = "Sign Up"
url = "signup"
weight = 4

# Dropdown menu
#[[Languages.en.menu.main]]
#weight = 4
#name = "Resources"
#hasChildren = true

  #[[Languages.en.menu.main]]
  #parent = "Resources"
  #name = "Installation"
  #url = "installation"
  #weight = 1

  #[[Languages.en.menu.main]]
  #parent = "Resources"
  #name = "Billing and Pricing"
  #url = "billing-pricing"
  #weight = 2

  #[[Languages.en.menu.main]]
  #parent = "Resources"
  #name = "Features"
  #url = "features"
  #weight = 3


################################### Franch Language ######################
#[Languages.fr]
#languageName = "Fr"
#languageCode = "fr-fr"
#weight = 2
#copyright = "Copyright © 2020 un thème Hugo par [Gethugothemes](https://gethugothemes.com/)"

# banner
#[Languages.fr.params.banner]
#title = "Comment pouvons nous aider?"
#subtitle = "Trouvez rapidement des conseils et des réponses auprès de notre équipe d'assistance ou contactez-nous."
#bg_image = "images/banner.jpg"
#placeholder = "Avoir une question? Il suffit de demander ici ou de saisir les termes"

# call to action
#[Languages.fr.params.cta]
#enable = true
#title = "Vous n'avez pas trouvé de réponse à votre question?"
#content = "Contactez-nous pour plus de détails sur les services supplémentaires et la tarification du travail personnalisé"
# call to action button
#[Languages.fr.params.cta.button]
#enable = true
#label = "Contactez nous"
#link = "contact"


################## french navigation #################
#[[Languages.fr.menu.main]]
#name = "Accueil"
#url = "/"
#weight = 1

#[[Languages.fr.menu.main]]
#name = "Faq"
#url = "faq"
#weight = 2

#[[Languages.fr.menu.main]]
#name = "contact"
#url = "contact"
#weight = 3

# Dropdown menu
#[[Languages.fr.menu.main]]
#weight = 4
#name = "docs"
#asChildren = true

  #[[Languages.fr.menu.main]]
  #parent = "docs"
  #name = "Installation"
  #url = "installation"
  #weight = 1

  #[[Languages.fr.menu.main]]
  #parent = "docs"
  #name = "Billing and Pricing"
  #url = "billing-pricing"
  #weight = 2

  #[[Languages.fr.menu.main]]
  #parent = "docs"
  #name = "Features"
  #url = "features"
  #weight = 3
